# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_view.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form(object):
    def setupUi(self, form):
        form.setObjectName("form")
        form.resize(660, 441)
        self.verticalLayout = QtWidgets.QVBoxLayout(form)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QHBoxLayout()
        self.header.setSpacing(6)
        self.header.setObjectName("header")
        self.shadow_selector = QtWidgets.QVBoxLayout()
        self.shadow_selector.setObjectName("shadow_selector")
        self.search = QtWidgets.QHBoxLayout()
        self.search.setObjectName("search")
        self.search_input = QtWidgets.QLineEdit(form)
        self.search_input.setObjectName("search_input")
        self.search.addWidget(self.search_input)
        self.search_button = QtWidgets.QPushButton(form)
        self.search_button.setObjectName("search_button")
        self.search.addWidget(self.search_button)
        self.shadow_selector.addLayout(self.search)
        self.variation_list = QtWidgets.QListWidget(form)
        self.variation_list.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.variation_list.setObjectName("variation_list")
        self.shadow_selector.addWidget(self.variation_list)
        self.header.addLayout(self.shadow_selector)
        self.persona_display = QtWidgets.QLabel(form)
        self.persona_display.setEnabled(True)
        self.persona_display.setMaximumSize(QtCore.QSize(250, 250))
        self.persona_display.setAutoFillBackground(False)
        self.persona_display.setText("")
        self.persona_display.setPixmap(QtGui.QPixmap("assets/placeholder.png"))
        self.persona_display.setScaledContents(False)
        self.persona_display.setObjectName("persona_display")
        self.header.addWidget(self.persona_display)
        self.verticalLayout.addLayout(self.header)
        self.persona_tabs = QtWidgets.QTabWidget(form)
        self.persona_tabs.setEnabled(True)
        self.persona_tabs.setStyleSheet("")
        self.persona_tabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.persona_tabs.setObjectName("persona_tabs")
        self.persona_3_tab = QtWidgets.QWidget()
        self.persona_3_tab.setEnabled(True)
        self.persona_3_tab.setStyleSheet("background-color: #4560A7")
        self.persona_3_tab.setObjectName("persona_3_tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.persona_3_tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.slash_3 = QtWidgets.QVBoxLayout()
        self.slash_3.setObjectName("slash_3")
        self.slash_3_label = QtWidgets.QLabel(self.persona_3_tab)
        self.slash_3_label.setStyleSheet("background-color: #F49C0B")
        self.slash_3_label.setAlignment(QtCore.Qt.AlignCenter)
        self.slash_3_label.setObjectName("slash_3_label")
        self.slash_3.addWidget(self.slash_3_label)
        self.slash_3_weakness = QtWidgets.QLabel(self.persona_3_tab)
        self.slash_3_weakness.setStyleSheet("background-color: #F49C0B;")
        self.slash_3_weakness.setTextFormat(QtCore.Qt.PlainText)
        self.slash_3_weakness.setAlignment(QtCore.Qt.AlignCenter)
        self.slash_3_weakness.setObjectName("slash_3_weakness")
        self.slash_3.addWidget(self.slash_3_weakness)
        self.horizontalLayout_2.addLayout(self.slash_3)
        self.strike_3 = QtWidgets.QVBoxLayout()
        self.strike_3.setObjectName("strike_3")
        self.strike_3_label = QtWidgets.QLabel(self.persona_3_tab)
        self.strike_3_label.setStyleSheet("background-color: #F49C0B")
        self.strike_3_label.setAlignment(QtCore.Qt.AlignCenter)
        self.strike_3_label.setObjectName("strike_3_label")
        self.strike_3.addWidget(self.strike_3_label)
        self.strike_3_weakness = QtWidgets.QLabel(self.persona_3_tab)
        self.strike_3_weakness.setStyleSheet("background-color: #F49C0B")
        self.strike_3_weakness.setAlignment(QtCore.Qt.AlignCenter)
        self.strike_3_weakness.setObjectName("strike_3_weakness")
        self.strike_3.addWidget(self.strike_3_weakness)
        self.horizontalLayout_2.addLayout(self.strike_3)
        self.pierce_3 = QtWidgets.QVBoxLayout()
        self.pierce_3.setObjectName("pierce_3")
        self.pierce_3_label = QtWidgets.QLabel(self.persona_3_tab)
        self.pierce_3_label.setStyleSheet("background-color: #F49C0B")
        self.pierce_3_label.setAlignment(QtCore.Qt.AlignCenter)
        self.pierce_3_label.setObjectName("pierce_3_label")
        self.pierce_3.addWidget(self.pierce_3_label)
        self.pierce_3_weakness = QtWidgets.QLabel(self.persona_3_tab)
        self.pierce_3_weakness.setStyleSheet("background-color: #F49C0B")
        self.pierce_3_weakness.setAlignment(QtCore.Qt.AlignCenter)
        self.pierce_3_weakness.setObjectName("pierce_3_weakness")
        self.pierce_3.addWidget(self.pierce_3_weakness)
        self.horizontalLayout_2.addLayout(self.pierce_3)
        self.fire_3 = QtWidgets.QVBoxLayout()
        self.fire_3.setObjectName("fire_3")
        self.fire_3_label = QtWidgets.QLabel(self.persona_3_tab)
        self.fire_3_label.setStyleSheet("background-color: #F33210")
        self.fire_3_label.setAlignment(QtCore.Qt.AlignCenter)
        self.fire_3_label.setObjectName("fire_3_label")
        self.fire_3.addWidget(self.fire_3_label)
        self.fire_3_weakness = QtWidgets.QLabel(self.persona_3_tab)
        self.fire_3_weakness.setStyleSheet("background-color: #F33210")
        self.fire_3_weakness.setAlignment(QtCore.Qt.AlignCenter)
        self.fire_3_weakness.setObjectName("fire_3_weakness")
        self.fire_3.addWidget(self.fire_3_weakness)
        self.horizontalLayout_2.addLayout(self.fire_3)
        self.ice_3 = QtWidgets.QVBoxLayout()
        self.ice_3.setObjectName("ice_3")
        self.ice_3_label = QtWidgets.QLabel(self.persona_3_tab)
        self.ice_3_label.setStyleSheet("background-color: #10B5FA")
        self.ice_3_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ice_3_label.setObjectName("ice_3_label")
        self.ice_3.addWidget(self.ice_3_label)
        self.ice_3_weakness = QtWidgets.QLabel(self.persona_3_tab)
        self.ice_3_weakness.setStyleSheet("background-color: #10B5FA")
        self.ice_3_weakness.setAlignment(QtCore.Qt.AlignCenter)
        self.ice_3_weakness.setObjectName("ice_3_weakness")
        self.ice_3.addWidget(self.ice_3_weakness)
        self.horizontalLayout_2.addLayout(self.ice_3)
        self.elec_3 = QtWidgets.QVBoxLayout()
        self.elec_3.setObjectName("elec_3")
        self.elec_3_label = QtWidgets.QLabel(self.persona_3_tab)
        self.elec_3_label.setStyleSheet("background-color: #FBFF28")
        self.elec_3_label.setAlignment(QtCore.Qt.AlignCenter)
        self.elec_3_label.setObjectName("elec_3_label")
        self.elec_3.addWidget(self.elec_3_label)
        self.elec_3_weakness = QtWidgets.QLabel(self.persona_3_tab)
        self.elec_3_weakness.setStyleSheet("background-color: #FBFF28")
        self.elec_3_weakness.setAlignment(QtCore.Qt.AlignCenter)
        self.elec_3_weakness.setObjectName("elec_3_weakness")
        self.elec_3.addWidget(self.elec_3_weakness)
        self.horizontalLayout_2.addLayout(self.elec_3)
        self.wind_3 = QtWidgets.QVBoxLayout()
        self.wind_3.setObjectName("wind_3")
        self.wind_3_label = QtWidgets.QLabel(self.persona_3_tab)
        self.wind_3_label.setStyleSheet("background-color: #17FF26")
        self.wind_3_label.setAlignment(QtCore.Qt.AlignCenter)
        self.wind_3_label.setObjectName("wind_3_label")
        self.wind_3.addWidget(self.wind_3_label)
        self.wind_3_weakness = QtWidgets.QLabel(self.persona_3_tab)
        self.wind_3_weakness.setStyleSheet("background-color: #17FF26")
        self.wind_3_weakness.setAlignment(QtCore.Qt.AlignCenter)
        self.wind_3_weakness.setObjectName("wind_3_weakness")
        self.wind_3.addWidget(self.wind_3_weakness)
        self.horizontalLayout_2.addLayout(self.wind_3)
        self.light_3 = QtWidgets.QVBoxLayout()
        self.light_3.setObjectName("light_3")
        self.light_3_label = QtWidgets.QLabel(self.persona_3_tab)
        self.light_3_label.setStyleSheet("background-color: #FDFFA3")
        self.light_3_label.setAlignment(QtCore.Qt.AlignCenter)
        self.light_3_label.setObjectName("light_3_label")
        self.light_3.addWidget(self.light_3_label)
        self.light_3_weakness = QtWidgets.QLabel(self.persona_3_tab)
        self.light_3_weakness.setStyleSheet("background-color: #FDFFA3")
        self.light_3_weakness.setAlignment(QtCore.Qt.AlignCenter)
        self.light_3_weakness.setObjectName("light_3_weakness")
        self.light_3.addWidget(self.light_3_weakness)
        self.horizontalLayout_2.addLayout(self.light_3)
        self.dark_3 = QtWidgets.QVBoxLayout()
        self.dark_3.setObjectName("dark_3")
        self.dark_3_label = QtWidgets.QLabel(self.persona_3_tab)
        self.dark_3_label.setStyleSheet("background-color: #2b2b2b; color:white;")
        self.dark_3_label.setAlignment(QtCore.Qt.AlignCenter)
        self.dark_3_label.setObjectName("dark_3_label")
        self.dark_3.addWidget(self.dark_3_label)
        self.dark_3_weakness = QtWidgets.QLabel(self.persona_3_tab)
        self.dark_3_weakness.setStyleSheet("background-color: #2b2b2b; color:white;")
        self.dark_3_weakness.setAlignment(QtCore.Qt.AlignCenter)
        self.dark_3_weakness.setObjectName("dark_3_weakness")
        self.dark_3.addWidget(self.dark_3_weakness)
        self.horizontalLayout_2.addLayout(self.dark_3)
        self.almi_3 = QtWidgets.QVBoxLayout()
        self.almi_3.setObjectName("almi_3")
        self.almi_3_label = QtWidgets.QLabel(self.persona_3_tab)
        self.almi_3_label.setStyleSheet("background-color: white;")
        self.almi_3_label.setAlignment(QtCore.Qt.AlignCenter)
        self.almi_3_label.setObjectName("almi_3_label")
        self.almi_3.addWidget(self.almi_3_label)
        self.almi_3_weakness = QtWidgets.QLabel(self.persona_3_tab)
        self.almi_3_weakness.setStyleSheet("background-color: white;")
        self.almi_3_weakness.setAlignment(QtCore.Qt.AlignCenter)
        self.almi_3_weakness.setObjectName("almi_3_weakness")
        self.almi_3.addWidget(self.almi_3_weakness)
        self.horizontalLayout_2.addLayout(self.almi_3)
        self.persona_tabs.addTab(self.persona_3_tab, "")
        self.persona_4_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.persona_4_tab.sizePolicy().hasHeightForWidth())
        self.persona_4_tab.setSizePolicy(sizePolicy)
        self.persona_4_tab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.persona_4_tab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.persona_4_tab.setStyleSheet("background-color: #FEEB4D")
        self.persona_4_tab.setObjectName("persona_4_tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.persona_4_tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.phys_4 = QtWidgets.QVBoxLayout()
        self.phys_4.setObjectName("phys_4")
        self.phys_4_label = QtWidgets.QLabel(self.persona_4_tab)
        self.phys_4_label.setStyleSheet("background-color: #F49C0B")
        self.phys_4_label.setAlignment(QtCore.Qt.AlignCenter)
        self.phys_4_label.setObjectName("phys_4_label")
        self.phys_4.addWidget(self.phys_4_label)
        self.phys_4_weakness = QtWidgets.QLabel(self.persona_4_tab)
        self.phys_4_weakness.setStyleSheet("background-color: #F49C0B")
        self.phys_4_weakness.setAlignment(QtCore.Qt.AlignCenter)
        self.phys_4_weakness.setObjectName("phys_4_weakness")
        self.phys_4.addWidget(self.phys_4_weakness)
        self.horizontalLayout.addLayout(self.phys_4)
        self.fire_4 = QtWidgets.QVBoxLayout()
        self.fire_4.setObjectName("fire_4")
        self.fire_4_label = QtWidgets.QLabel(self.persona_4_tab)
        self.fire_4_label.setStyleSheet("background-color: #F33210")
        self.fire_4_label.setAlignment(QtCore.Qt.AlignCenter)
        self.fire_4_label.setObjectName("fire_4_label")
        self.fire_4.addWidget(self.fire_4_label)
        self.fire_4_weakness = QtWidgets.QLabel(self.persona_4_tab)
        self.fire_4_weakness.setStyleSheet("background-color: #F33210")
        self.fire_4_weakness.setAlignment(QtCore.Qt.AlignCenter)
        self.fire_4_weakness.setObjectName("fire_4_weakness")
        self.fire_4.addWidget(self.fire_4_weakness)
        self.horizontalLayout.addLayout(self.fire_4)
        self.ice_4 = QtWidgets.QVBoxLayout()
        self.ice_4.setObjectName("ice_4")
        self.ice_4_label = QtWidgets.QLabel(self.persona_4_tab)
        self.ice_4_label.setStyleSheet("background-color: #10B5FA")
        self.ice_4_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ice_4_label.setObjectName("ice_4_label")
        self.ice_4.addWidget(self.ice_4_label)
        self.ice_4_weakness = QtWidgets.QLabel(self.persona_4_tab)
        self.ice_4_weakness.setStyleSheet("background-color: #10B5FA")
        self.ice_4_weakness.setAlignment(QtCore.Qt.AlignCenter)
        self.ice_4_weakness.setObjectName("ice_4_weakness")
        self.ice_4.addWidget(self.ice_4_weakness)
        self.horizontalLayout.addLayout(self.ice_4)
        self.elec_4 = QtWidgets.QVBoxLayout()
        self.elec_4.setObjectName("elec_4")
        self.elec_4_label = QtWidgets.QLabel(self.persona_4_tab)
        self.elec_4_label.setStyleSheet("background-color: #FBFF28")
        self.elec_4_label.setAlignment(QtCore.Qt.AlignCenter)
        self.elec_4_label.setObjectName("elec_4_label")
        self.elec_4.addWidget(self.elec_4_label)
        self.elec_4_weakness = QtWidgets.QLabel(self.persona_4_tab)
        self.elec_4_weakness.setStyleSheet("background-color: #FBFF28")
        self.elec_4_weakness.setAlignment(QtCore.Qt.AlignCenter)
        self.elec_4_weakness.setObjectName("elec_4_weakness")
        self.elec_4.addWidget(self.elec_4_weakness)
        self.horizontalLayout.addLayout(self.elec_4)
        self.wind_4 = QtWidgets.QVBoxLayout()
        self.wind_4.setObjectName("wind_4")
        self.wind_4_label = QtWidgets.QLabel(self.persona_4_tab)
        self.wind_4_label.setStyleSheet("background-color: #17FF26")
        self.wind_4_label.setAlignment(QtCore.Qt.AlignCenter)
        self.wind_4_label.setObjectName("wind_4_label")
        self.wind_4.addWidget(self.wind_4_label)
        self.wind_4_weakness = QtWidgets.QLabel(self.persona_4_tab)
        self.wind_4_weakness.setStyleSheet("background-color: #17FF26")
        self.wind_4_weakness.setAlignment(QtCore.Qt.AlignCenter)
        self.wind_4_weakness.setObjectName("wind_4_weakness")
        self.wind_4.addWidget(self.wind_4_weakness)
        self.horizontalLayout.addLayout(self.wind_4)
        self.light_4 = QtWidgets.QVBoxLayout()
        self.light_4.setObjectName("light_4")
        self.light_4_label = QtWidgets.QLabel(self.persona_4_tab)
        self.light_4_label.setStyleSheet("background-color: #FDFFA3")
        self.light_4_label.setAlignment(QtCore.Qt.AlignCenter)
        self.light_4_label.setObjectName("light_4_label")
        self.light_4.addWidget(self.light_4_label)
        self.light_4_weakness = QtWidgets.QLabel(self.persona_4_tab)
        self.light_4_weakness.setStyleSheet("background-color: #FDFFA3")
        self.light_4_weakness.setAlignment(QtCore.Qt.AlignCenter)
        self.light_4_weakness.setObjectName("light_4_weakness")
        self.light_4.addWidget(self.light_4_weakness)
        self.horizontalLayout.addLayout(self.light_4)
        self.dark_4 = QtWidgets.QVBoxLayout()
        self.dark_4.setObjectName("dark_4")
        self.dark_4_label = QtWidgets.QLabel(self.persona_4_tab)
        self.dark_4_label.setStyleSheet("background-color: rgb(43, 43, 43); color: white;")
        self.dark_4_label.setAlignment(QtCore.Qt.AlignCenter)
        self.dark_4_label.setObjectName("dark_4_label")
        self.dark_4.addWidget(self.dark_4_label)
        self.dark_4_weakness = QtWidgets.QLabel(self.persona_4_tab)
        self.dark_4_weakness.setStyleSheet("background-color: rgb(43, 43, 43); color: white;")
        self.dark_4_weakness.setAlignment(QtCore.Qt.AlignCenter)
        self.dark_4_weakness.setObjectName("dark_4_weakness")
        self.dark_4.addWidget(self.dark_4_weakness)
        self.horizontalLayout.addLayout(self.dark_4)
        self.almi_4 = QtWidgets.QVBoxLayout()
        self.almi_4.setObjectName("almi_4")
        self.almi_4_label = QtWidgets.QLabel(self.persona_4_tab)
        self.almi_4_label.setStyleSheet("background-color: white;")
        self.almi_4_label.setAlignment(QtCore.Qt.AlignCenter)
        self.almi_4_label.setObjectName("almi_4_label")
        self.almi_4.addWidget(self.almi_4_label)
        self.almi_4_weakness = QtWidgets.QLabel(self.persona_4_tab)
        self.almi_4_weakness.setStyleSheet("background-color: white;")
        self.almi_4_weakness.setAlignment(QtCore.Qt.AlignCenter)
        self.almi_4_weakness.setObjectName("almi_4_weakness")
        self.almi_4.addWidget(self.almi_4_weakness)
        self.horizontalLayout.addLayout(self.almi_4)
        self.persona_tabs.addTab(self.persona_4_tab, "")
        self.persona_5_tab = QtWidgets.QWidget()
        self.persona_5_tab.setStyleSheet("background-color: rgb(191, 21, 30);")
        self.persona_5_tab.setObjectName("persona_5_tab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.persona_5_tab)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.phys_5 = QtWidgets.QVBoxLayout()
        self.phys_5.setObjectName("phys_5")
        self.phys_5_label = QtWidgets.QLabel(self.persona_5_tab)
        self.phys_5_label.setStyleSheet("background-color: rgb(242, 163, 9);")
        self.phys_5_label.setAlignment(QtCore.Qt.AlignCenter)
        self.phys_5_label.setObjectName("phys_5_label")
        self.phys_5.addWidget(self.phys_5_label)
        self.phys_5_weakness = QtWidgets.QLabel(self.persona_5_tab)
        self.phys_5_weakness.setStyleSheet("background-color: rgb(242, 163, 9);")
        self.phys_5_weakness.setAlignment(QtCore.Qt.AlignCenter)
        self.phys_5_weakness.setObjectName("phys_5_weakness")
        self.phys_5.addWidget(self.phys_5_weakness)
        self.horizontalLayout_3.addLayout(self.phys_5)
        self.gun_5 = QtWidgets.QVBoxLayout()
        self.gun_5.setObjectName("gun_5")
        self.gun_5_label = QtWidgets.QLabel(self.persona_5_tab)
        self.gun_5_label.setStyleSheet("background-color: rgb(242, 163, 9);")
        self.gun_5_label.setAlignment(QtCore.Qt.AlignCenter)
        self.gun_5_label.setObjectName("gun_5_label")
        self.gun_5.addWidget(self.gun_5_label)
        self.gun_5_weakness = QtWidgets.QLabel(self.persona_5_tab)
        self.gun_5_weakness.setStyleSheet("background-color: rgb(242, 163, 9);")
        self.gun_5_weakness.setAlignment(QtCore.Qt.AlignCenter)
        self.gun_5_weakness.setObjectName("gun_5_weakness")
        self.gun_5.addWidget(self.gun_5_weakness)
        self.horizontalLayout_3.addLayout(self.gun_5)
        self.fire_5 = QtWidgets.QVBoxLayout()
        self.fire_5.setObjectName("fire_5")
        self.fire_5_label = QtWidgets.QLabel(self.persona_5_tab)
        self.fire_5_label.setStyleSheet("background-color: rgb(242, 49, 14);")
        self.fire_5_label.setAlignment(QtCore.Qt.AlignCenter)
        self.fire_5_label.setObjectName("fire_5_label")
        self.fire_5.addWidget(self.fire_5_label)
        self.fire_5_weakness = QtWidgets.QLabel(self.persona_5_tab)
        self.fire_5_weakness.setStyleSheet("background-color: rgb(242, 49, 14);")
        self.fire_5_weakness.setAlignment(QtCore.Qt.AlignCenter)
        self.fire_5_weakness.setObjectName("fire_5_weakness")
        self.fire_5.addWidget(self.fire_5_weakness)
        self.horizontalLayout_3.addLayout(self.fire_5)
        self.ice_5 = QtWidgets.QVBoxLayout()
        self.ice_5.setObjectName("ice_5")
        self.ice_5_label = QtWidgets.QLabel(self.persona_5_tab)
        self.ice_5_label.setStyleSheet("background-color: rgb(16, 182, 251);")
        self.ice_5_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ice_5_label.setObjectName("ice_5_label")
        self.ice_5.addWidget(self.ice_5_label)
        self.ice_5_weakness = QtWidgets.QLabel(self.persona_5_tab)
        self.ice_5_weakness.setStyleSheet("background-color: rgb(16, 182, 251);")
        self.ice_5_weakness.setAlignment(QtCore.Qt.AlignCenter)
        self.ice_5_weakness.setObjectName("ice_5_weakness")
        self.ice_5.addWidget(self.ice_5_weakness)
        self.horizontalLayout_3.addLayout(self.ice_5)
        self.elec_5 = QtWidgets.QVBoxLayout()
        self.elec_5.setObjectName("elec_5")
        self.elec_5_label = QtWidgets.QLabel(self.persona_5_tab)
        self.elec_5_label.setStyleSheet("background-color: rgb(250, 255, 39);")
        self.elec_5_label.setAlignment(QtCore.Qt.AlignCenter)
        self.elec_5_label.setObjectName("elec_5_label")
        self.elec_5.addWidget(self.elec_5_label)
        self.elec_5_weakness = QtWidgets.QLabel(self.persona_5_tab)
        self.elec_5_weakness.setStyleSheet("background-color: rgb(250, 255, 39);")
        self.elec_5_weakness.setAlignment(QtCore.Qt.AlignCenter)
        self.elec_5_weakness.setObjectName("elec_5_weakness")
        self.elec_5.addWidget(self.elec_5_weakness)
        self.horizontalLayout_3.addLayout(self.elec_5)
        self.wind_5 = QtWidgets.QVBoxLayout()
        self.wind_5.setObjectName("wind_5")
        self.wind_5_label = QtWidgets.QLabel(self.persona_5_tab)
        self.wind_5_label.setStyleSheet("background-color: rgb(17, 255, 33);")
        self.wind_5_label.setAlignment(QtCore.Qt.AlignCenter)
        self.wind_5_label.setObjectName("wind_5_label")
        self.wind_5.addWidget(self.wind_5_label)
        self.wind_5_weakness = QtWidgets.QLabel(self.persona_5_tab)
        self.wind_5_weakness.setStyleSheet("background-color: rgb(17, 255, 33);")
        self.wind_5_weakness.setAlignment(QtCore.Qt.AlignCenter)
        self.wind_5_weakness.setObjectName("wind_5_weakness")
        self.wind_5.addWidget(self.wind_5_weakness)
        self.horizontalLayout_3.addLayout(self.wind_5)
        self.psy_5 = QtWidgets.QVBoxLayout()
        self.psy_5.setObjectName("psy_5")
        self.psy_5_label = QtWidgets.QLabel(self.persona_5_tab)
        self.psy_5_label.setStyleSheet("background-color: rgb(229, 110, 236);")
        self.psy_5_label.setAlignment(QtCore.Qt.AlignCenter)
        self.psy_5_label.setObjectName("psy_5_label")
        self.psy_5.addWidget(self.psy_5_label)
        self.psy_5_weakness = QtWidgets.QLabel(self.persona_5_tab)
        self.psy_5_weakness.setStyleSheet("background-color: rgb(229, 110, 236);")
        self.psy_5_weakness.setAlignment(QtCore.Qt.AlignCenter)
        self.psy_5_weakness.setObjectName("psy_5_weakness")
        self.psy_5.addWidget(self.psy_5_weakness)
        self.horizontalLayout_3.addLayout(self.psy_5)
        self.nuke_5 = QtWidgets.QVBoxLayout()
        self.nuke_5.setObjectName("nuke_5")
        self.nuke_5_label = QtWidgets.QLabel(self.persona_5_tab)
        self.nuke_5_label.setStyleSheet("background-color: rgb(19, 255, 249);")
        self.nuke_5_label.setAlignment(QtCore.Qt.AlignCenter)
        self.nuke_5_label.setObjectName("nuke_5_label")
        self.nuke_5.addWidget(self.nuke_5_label)
        self.nuke_5_weakness = QtWidgets.QLabel(self.persona_5_tab)
        self.nuke_5_weakness.setStyleSheet("background-color: rgb(19, 255, 249);")
        self.nuke_5_weakness.setAlignment(QtCore.Qt.AlignCenter)
        self.nuke_5_weakness.setObjectName("nuke_5_weakness")
        self.nuke_5.addWidget(self.nuke_5_weakness)
        self.horizontalLayout_3.addLayout(self.nuke_5)
        self.bless_5 = QtWidgets.QVBoxLayout()
        self.bless_5.setObjectName("bless_5")
        self.bless_5_label = QtWidgets.QLabel(self.persona_5_tab)
        self.bless_5_label.setStyleSheet("background-color: rgb(250, 255, 158);")
        self.bless_5_label.setAlignment(QtCore.Qt.AlignCenter)
        self.bless_5_label.setObjectName("bless_5_label")
        self.bless_5.addWidget(self.bless_5_label)
        self.bless_5_weakness = QtWidgets.QLabel(self.persona_5_tab)
        self.bless_5_weakness.setStyleSheet("background-color: rgb(250, 255, 158);")
        self.bless_5_weakness.setAlignment(QtCore.Qt.AlignCenter)
        self.bless_5_weakness.setObjectName("bless_5_weakness")
        self.bless_5.addWidget(self.bless_5_weakness)
        self.horizontalLayout_3.addLayout(self.bless_5)
        self.curse_5 = QtWidgets.QVBoxLayout()
        self.curse_5.setObjectName("curse_5")
        self.curse_5_label = QtWidgets.QLabel(self.persona_5_tab)
        self.curse_5_label.setStyleSheet("background-color: rgb(237, 0, 42);")
        self.curse_5_label.setAlignment(QtCore.Qt.AlignCenter)
        self.curse_5_label.setObjectName("curse_5_label")
        self.curse_5.addWidget(self.curse_5_label)
        self.curse_5_weakness = QtWidgets.QLabel(self.persona_5_tab)
        self.curse_5_weakness.setStyleSheet("background-color: rgb(237, 0, 42);")
        self.curse_5_weakness.setAlignment(QtCore.Qt.AlignCenter)
        self.curse_5_weakness.setObjectName("curse_5_weakness")
        self.curse_5.addWidget(self.curse_5_weakness)
        self.horizontalLayout_3.addLayout(self.curse_5)
        self.almi_5 = QtWidgets.QVBoxLayout()
        self.almi_5.setObjectName("almi_5")
        self.almi_5_label = QtWidgets.QLabel(self.persona_5_tab)
        self.almi_5_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.almi_5_label.setAlignment(QtCore.Qt.AlignCenter)
        self.almi_5_label.setObjectName("almi_5_label")
        self.almi_5.addWidget(self.almi_5_label)
        self.almi_5_weakness = QtWidgets.QLabel(self.persona_5_tab)
        self.almi_5_weakness.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.almi_5_weakness.setAlignment(QtCore.Qt.AlignCenter)
        self.almi_5_weakness.setObjectName("almi_5_weakness")
        self.almi_5.addWidget(self.almi_5_weakness)
        self.horizontalLayout_3.addLayout(self.almi_5)
        self.persona_tabs.addTab(self.persona_5_tab, "")
        self.verticalLayout.addWidget(self.persona_tabs)

        self.retranslateUi(form)
        self.persona_tabs.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(form)

    def retranslateUi(self, form):
        _translate = QtCore.QCoreApplication.translate
        form.setWindowTitle(_translate("form", "Persona Weakness Finder"))
        self.search_input.setPlaceholderText(_translate("form", "Persona name search"))
        self.search_button.setText(_translate("form", "Search"))
        self.slash_3_label.setText(_translate("form", "Slash"))
        self.slash_3_weakness.setText(_translate("form", "-"))
        self.strike_3_label.setText(_translate("form", "Strike"))
        self.strike_3_weakness.setText(_translate("form", "-"))
        self.pierce_3_label.setText(_translate("form", "Pierce"))
        self.pierce_3_weakness.setText(_translate("form", "-"))
        self.fire_3_label.setText(_translate("form", "Fire"))
        self.fire_3_weakness.setText(_translate("form", "-"))
        self.ice_3_label.setText(_translate("form", "Ice"))
        self.ice_3_weakness.setText(_translate("form", "-"))
        self.elec_3_label.setText(_translate("form", "Elec"))
        self.elec_3_weakness.setText(_translate("form", "-"))
        self.wind_3_label.setText(_translate("form", "Wind"))
        self.wind_3_weakness.setText(_translate("form", "-"))
        self.light_3_label.setText(_translate("form", "Light"))
        self.light_3_weakness.setText(_translate("form", "-"))
        self.dark_3_label.setText(_translate("form", "Dark"))
        self.dark_3_weakness.setText(_translate("form", "-"))
        self.almi_3_label.setText(_translate("form", "Almi"))
        self.almi_3_weakness.setText(_translate("form", "-"))
        self.persona_tabs.setTabText(self.persona_tabs.indexOf(self.persona_3_tab), _translate("form", "Persona 3"))
        self.phys_4_label.setText(_translate("form", "Phys"))
        self.phys_4_weakness.setText(_translate("form", "-"))
        self.fire_4_label.setText(_translate("form", "Fire"))
        self.fire_4_weakness.setText(_translate("form", "-"))
        self.ice_4_label.setText(_translate("form", "Ice"))
        self.ice_4_weakness.setText(_translate("form", "-"))
        self.elec_4_label.setText(_translate("form", "Elec"))
        self.elec_4_weakness.setText(_translate("form", "-"))
        self.wind_4_label.setText(_translate("form", "Wind"))
        self.wind_4_weakness.setText(_translate("form", "-"))
        self.light_4_label.setText(_translate("form", "Light"))
        self.light_4_weakness.setText(_translate("form", "-"))
        self.dark_4_label.setText(_translate("form", "Dark"))
        self.dark_4_weakness.setText(_translate("form", "-"))
        self.almi_4_label.setText(_translate("form", "Almi"))
        self.almi_4_weakness.setText(_translate("form", "-"))
        self.persona_tabs.setTabText(self.persona_tabs.indexOf(self.persona_4_tab), _translate("form", "Persona 4"))
        self.phys_5_label.setText(_translate("form", "Phys"))
        self.phys_5_weakness.setText(_translate("form", "-"))
        self.gun_5_label.setText(_translate("form", "Gun"))
        self.gun_5_weakness.setText(_translate("form", "-"))
        self.fire_5_label.setText(_translate("form", "Fire"))
        self.fire_5_weakness.setText(_translate("form", "-"))
        self.ice_5_label.setText(_translate("form", "Ice"))
        self.ice_5_weakness.setText(_translate("form", "-"))
        self.elec_5_label.setText(_translate("form", "Elec"))
        self.elec_5_weakness.setText(_translate("form", "-"))
        self.wind_5_label.setText(_translate("form", "Wind"))
        self.wind_5_weakness.setText(_translate("form", "-"))
        self.psy_5_label.setText(_translate("form", "Psy"))
        self.psy_5_weakness.setText(_translate("form", "-"))
        self.nuke_5_label.setText(_translate("form", "Nuke"))
        self.nuke_5_weakness.setText(_translate("form", "-"))
        self.bless_5_label.setText(_translate("form", "Bless"))
        self.bless_5_weakness.setText(_translate("form", "-"))
        self.curse_5_label.setText(_translate("form", "Curse"))
        self.curse_5_weakness.setText(_translate("form", "-"))
        self.almi_5_label.setText(_translate("form", "Almi"))
        self.almi_5_weakness.setText(_translate("form", "-"))
        self.persona_tabs.setTabText(self.persona_tabs.indexOf(self.persona_5_tab), _translate("form", "Persona 5"))


