avenger_knight_weaknesses = {
    "Persona 3 - The Journey": {
        "Slash": "Null",
        "Strike": "-",
        "Pierce": "-",
        "Fire": "-",
        "Ice": "-",
        "Elec": "-",
        "Wind": "-",
        "Light": "Weak",
        "Dark": "-",
        "Almi": "-",
    },
    "Persona 3 - The Answer": {
        "Slash": "-",
        "Strike": "-",
        "Pierce": "Repel",
        "Fire": "-",
        "Ice": "-",
        "Elec": "Drain",
        "Wind": "-",
        "Light": "Null",
        "Dark": "Repel",
        "Almi": "-",
    },
    "Persona 4 - Boss": {
        "Phys": "Strong",
        "Fire": "-",
        "Ice": "-",
        "Elec": "-",
        "Wind": "-",
        "Light": "Null",
        "Dark": "Null",
        "Almi": "-",
    },
    "Persona 4 - Normal Enemy": {
        "Phys": "Strong",
        "Fire": "-",
        "Ice": "-",
        "Elec": "-",
        "Wind": "-",
        "Light": "Weak",
        "Dark": "-",
        "Almi": "-",
    },
    "Persona 4 Golden - Boss": {
        "Phys": "-",
        "Fire": "Weak",
        "Ice": "-",
        "Elec": "-",
        "Wind": "-",
        "Light": "Null",
        "Dark": "Null",
        "Almi": "-",
    },
    "Persona 4 Golden - Normal Enemy": {
        "Phys": "-",
        "Fire": "Weak",
        "Ice": "-",
        "Elec": "-",
        "Wind": "-",
        "Light": "-",
        "Dark": "-",
        "Almi": "-",
    }
}
